FROM python:3.10-slim

WORKDIR /app

# Insttall OS dependencies (required for sklearn)
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
fastapi \
uvicorn \
scikit-learn \
mlflow \
joblib \
boto3

COPY api/ api/

# Expose API port
EXPOSE 8000

# Start FastAPI
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
