FROM python:3.10-slim

WORKDIR /app

# Insttall OS dependencies (required for sklearn)
RUN pip install streamlit requests

COPY ui/ ui/

# Start FastAPI
CMD ["streamlit", "run", "ui/app.py"]